version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:5080
    volumes:
      - .:/code
    ports:
      - 5080:5080
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-4!vqi$$mxs$$*-8p@blvwnnn$$qo5cdqd=8_nl@ah%rxuble57y&6"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
