# Generated by Django 4.1.3 on 2023-02-09 06:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_blogcategories_blog_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='update datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='post title')),
                ('image', models.ImageField(upload_to='blog/blog_title/', verbose_name='post image')),
                ('body', ckeditor.fields.RichTextField(verbose_name='post text')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='update datetime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='blogcategories',
            name='count_search',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='postcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blogs.blogcategories', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='postcategories',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blogs.post', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='categorysearchhistory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_history_search', to='blogs.blogcategories', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='categorysearchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search_category', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
