# Generated by Django 4.1.3 on 2023-03-18 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('default_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blogs.blogcategories', verbose_name='creator'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostCategories',
        ),
    ]
