# Generated by Django 4.1.3 on 2023-03-22 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_alter_post_options_alter_post_managers_post_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategories',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorysearchhistory',
            options={'verbose_name': 'CategorySearchHistory', 'verbose_name_plural': 'CategorySearchHistories'},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='this is a test for description', max_length=1000, verbose_name='description about this post'),
        ),
        migrations.AlterField(
            model_name='categorysearchhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_search_category', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blogs.blogcategories', verbose_name='category'),
        ),
    ]
