# Generated by Django 4.1.3 on 2023-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogcategories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dis_like',
            field=models.PositiveIntegerField(default=20, verbose_name='number of unlike'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(default=50, verbose_name='number of like'),
            preserve_default=False,
        ),
    ]
