# Generated by Django 4.1.3 on 2022-12-23 08:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_alter_comments_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 8, 4, 47, 660545, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='products',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 8, 4, 47, 658470, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_per', models.IntegerField(verbose_name='discount percentage')),
                ('number_of_users', models.IntegerField(verbose_name='discount for number of users')),
                ('date_expiry', models.DateTimeField(verbose_name='Date expiry')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime(2022, 12, 23, 8, 4, 47, 659558, tzinfo=datetime.timezone.utc))),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='products.products', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to=settings.AUTH_USER_MODEL, verbose_name='discount')),
            ],
        ),
    ]
