# Generated by Django 4.1.3 on 2022-12-23 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_comments_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 0, 41, 14, 902041)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 0, 41, 14, 901355)),
        ),
        migrations.AlterField(
            model_name='products',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 0, 41, 14, 900604)),
        ),
    ]
