# Generated by Django 4.1.3 on 2023-01-01 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_comments_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 20, 50, 6, 80405)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 20, 50, 6, 79773)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='number_of_users',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount for number of users'),
        ),
        migrations.AlterField(
            model_name='products',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 20, 50, 6, 79016)),
        ),
    ]
