# Generated by Django 4.1.3 on 2023-01-09 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_comments_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 17, 0, 13, 89977, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='products',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 17, 0, 13, 89166, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
