# Generated by Django 4.1.3 on 2023-02-09 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_comments_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 10, 24, 24, 417681)),
        ),
        migrations.AlterField(
            model_name='products',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 10, 24, 24, 416917)),
        ),
    ]
